spring:
  application:
    name: ben-sso
  redis:
    host: redis.appx.host
    port: 6379
    database: 0
dubbo:
  registry:
    id: main-registry
    address: zookeeper://zookeeper.appx.host:2181
  application:
    id: ben-sso
    name: ben-sso
server:
  port: 23301
#debug: true
ben:
  user-service:
    version: 1.0
  group-service:
    version: 1.0
  privilege-service:
    version: 1.0
