
eureka:
  client:
    service-url:
      defaultZone: http://eureka.appx.host:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    user-service:
      path: /**
      serviceId: provider-user-service
server:
  port: 8080
spring:
  application:
    name: gateway-zuul