server:
  port: 23100
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://mysql.appx.host:3306/ben?useUnicode=true&useSSL=false&characterEncoding=utf8
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
debug: true