spring:
  application:
    name: provider-user-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://mysql.appx.host:3306/ben?useUnicode=true&useSSL=false&characterEncoding=utf8
dubbo:
  registry:
    id: main-registry
    address: zookeeper://zookeeper.appx.host:2181
  application:
    id: provider-user-service
    name: provider-user-service
  protocol:
    id: dubbo
    name: dubbo
    host: localhost
    port: 22201
  scan:
    base-packages: com.spawpaw.ben.provider.service
mybatis:
  mapper-locations: classpath*:mapper/*.xml
#  mapper-locations: classpath*:/com/spawpaw/ben/provider/dao
debug: true